name: Docker Image CI

#Se dispara la acción cada vez que se haga un push o un pull request a "main"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#Trabajos que vamos a hacer
jobs:

  build:

    #Trabajamos sobre Ubuntu ya que trae ciertas configuaciones como el Docker Daemon
    #que nos permite ejecutar comandos de Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: |
        docker build -t juancamilomontoya/docker-graphql:0.0.2 .

    - name: Push Docker image
      run: |
        docker push juancamilomontoya/docker-graphql:0.0.2 .
